language: php

env:

  global:
    - 'FTP_USER=rhesty-chahya'
    - 'FTP_PASS=cahya123'

script:
# script buat folder baru
#- "curl -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com -Q 'mkd public_html/praktek-4c'"
 # script upload file *.php
    - "curl -T koneksi.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
    - "curl -T simpan-baru.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
    - "curl -T update.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
    - "curl -T hapus.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
    - "curl -T main.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
    - "curl -T Edit-from.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"
    - "curl -T tambah.php -u $FTP_USER:$FTP_PASS ftp://files.000webhost.com/public_html/"